#!/usr/bin/env bash    

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # script's directory
OUTDIR="$DIR/../imlook4d-exports"
echo "DIR = " $DIR
echo "OUTDIR = " $OUTDIR


# Get revision number
cd $DIR

rev=$(zenity --list  --column "tag"  $(git tag --sort=-creatordate ))  # Tags sorted by date
rc=$?; if [[ $rc != 0 ]]; then echo 'Canceled'; exit $rc; fi  # Exit if cancelled

echo "Selected tag =  $rev"


# Create name
NAME="imlook4d_($rev).zip"
ZIPFILE="$OUTDIR/$NAME"

# Export to zip file
echo "Write tag = \"$rev:imlook4d\" to zip-file = \"$NAME\""  
git archive "$rev:imlook4d" --output "$ZIPFILE"  
zip -u "$ZIPFILE"

# Update version file inside zip file
cd "$OUTDIR"
echo  "Write text \"$rev\" to file \"version.txt\""
echo -n "$rev" > version.txt
echo  "Update file \"version.txt\" in zip-file"
zip -u "$ZIPFILE" "version.txt"


# Clean up temporary files
rm version.txt

echo "------------------------------------------------------------------------------------ "
echo "CREATED ARCHIVE = \"$NAME\""
echo "IN FOLDER       = \"$OUTDIR\""
echo "------------------------------------------------------------------------------------ "

read -n 1 -s -r -p "DONE!  (Press any key to quit!)"
exit
