#!/usr/bin/env bash    

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # script's directory
OUTDIR="$DIR/../imlook4d-exports"
echo "DIR = " $DIR
echo "OUTDIR = " $OUTDIR


# Get revision number
cd $DIR

rev=$(zenity --list  --column "tag"  $(git tag --sort=-creatordate ))  # Tags sorted by date
rc=$?; if [[ $rc != 0 ]]; then echo 'Canceled'; exit $rc; fi  # Exit if cancelled

echo "Selected tag =  $rev"


# Create name
NAME="imlook4d_($rev).zip"
ZIPFILE="$OUTDIR/$NAME"

# Export to zip file
git archive $rev --output "$ZIPFILE"  
zip -u "$ZIPFILE"

# Make version file inside zip file
cd "$OUTDIR"
mkdir imlook4d
echo -n "$rev" > imlook4d/version.txt
zip -u "$ZIPFILE" "imlook4d/version.txt"
echo zip -u "$ZIPFILE" "imlook4d/version.txt"

# Remove from zip file
zip -d "$ZIPFILE" imlook4d-export-to-zip TODO.txt

# Clean up temporary files
rm "imlook4d/version.txt"
rmdir imlook4d

echo "------------------------------------------------------------------------------------ "
echo "CREATED ARCHIVE = \"$NAME\""
echo "IN FOLDER       = \"$OUTDIR\""
echo "------------------------------------------------------------------------------------ "

read -n 1 -s -r -p "DONE!  (Press any key to quit!)"
exit
