#!/usr/bin/env bash    

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # script's directory
OUTDIR="$DIR/../imlook4d-exports"
echo "DIR = " $DIR
echo "OUTDIR = " $OUTDIR


# Get revision number
cd $DIR

echo "Latest tag = $(git tag --sort=-creatordate |  head -n 1)"

rev=$(zenity --list  --column "tag"  $(git tag --sort=-creatordate ))  # Tags sorted by date
rc=$?; if [[ $rc != 0 ]]; then echo 'Canceled'; exit $rc; fi  # Exit if cancelled

echo "Selected tag =  $rev"


# Create name
NAME="imlook4d_($rev).zip"
ZIPFILE="$OUTDIR/$NAME"

# Export to zip file
echo "Write tag = \"$rev:imlook4d\" to zip-file = \"$NAME\""  
git archive "$rev:imlook4d" --output "$ZIPFILE"  
zip -u "$ZIPFILE"

# Update version file inside zip file
cd "$OUTDIR"
echo  "Write text \"$rev\" to file \"version.txt\""
echo -n "$rev" > version.txt
echo  "Update file \"version.txt\" in zip-file"
zip -u "$ZIPFILE" "version.txt"


# Clean up temporary files
rm version.txt

echo "------------------------------------------------------------------------------------ "
echo "CREATED ARCHIVE = \"$NAME\""
echo "IN FOLDER       = \"$OUTDIR\""
echo "------------------------------------------------------------------------------------ "


# Send to Google Drive

cd '/Users/jan/Documents/Projects/imlook4d/imlook4d_DEVELOP/release to google drive/'

echo "------------------------------------------------------------------------------------ "
echo "SEND TO GOOGLE DRIVE : "
./send_to_google_api_folder.py '1A_3nhoQsr4_djNum_yiFcO4dm3Ctbxkx' "$ZIPFILE" # imlook4d-site/downloads/Current release
echo "------------------------------------------------------------------------------------ "


echo "------------------------------------------------------------------------------------ "
echo "Update latest_releases.txt : "
fileID=$(cat '/tmp/gdrive_id.txt')
echo REV=$rev
echo "$rev    https://drive.google.com/uc?export=download&id=$fileID" > '/tmp/gdrive_id.txt'  
# Relies on local version of  '/Users/jan/Google Drive/imlook4d-site/downloads/latest_releases.txt'  being up to date
cat '/tmp/gdrive_id.txt' '/Users/jan/Google Drive/imlook4d-site/downloads/latest_releases.txt' > '/tmp/latest_releases.txt' 
mv '/tmp/latest_releases.txt' '/Users/jan/Google Drive/imlook4d-site/downloads/latest_releases.txt'
./send_to_google_api_file.py '13mGVhbnZYUyr6BWq4mXTTo12PvM7gykJ' '/Users/jan/Google Drive/imlook4d-site/downloads/latest_releases.txt'  # imlook4d-site/downloads
echo "------------------------------------------------------------------------------------ "




read -n 1 -s -r -p "DONE!  (Press any key to quit!)"
exit
