function S = roi_table_gui(data, name, columnTitles)
% Help
S.fh = figure('units','pixels',...
              'position',[500 500 800 860],...
              'menubar','none',...
              'name',name,...
              'numbertitle','off',...
              'resize','off');
          
S.fh.Resize='on'

S.tb = uitable('unit','pix',...
                 'position',[10 20 780 830],...
                 'fontsize',12);         
             
set(S.tb, 'Data', data);
S.tb.ColumnWidth = {200, 'auto'}
%S.tb.ColumnWidth{1}= 200;  % Wider first column

S.tb.ColumnName = [ 'name' columnTitles];


%uiwait(S.fh) 