%function webhandle=displayHTML(basePath,title,text1,text2,text3)
function webhandle=displayHTML(basePath,title,varargin)


                       allText=['text:// ' ...
                                '<html>' ... 
                                '<title>' title '</title>'... 
                                    '<base href="' ['file://localhost/' basePath '\HELP\' ] '" />' ...
                                    varargin{:}...
                                '</html>' ];


%                        allText=['text:// ' ...
%                                 '<html>' ... 
%                                 '<title>' title '</title>'... 
%                                     varargin{:}...
%                                 '</html>' ];
                            
                       % Display in web browser, and store handles
                       [stat, webhandle] =web(allText,'-noaddressbox');    